"""foundation: businesses, users, feature_flags

Revision ID: c1efc82196c2
Revises: 
Create Date: 2026-08-29 00:51:59.149217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1efc82196c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('cr_no', sa.String(length=100), nullable=True),
    sa.Column('phone_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('bank_account_name', sa.String(length=255), nullable=True),
    sa.Column('bank_iban_or_no', sa.String(length=100), nullable=True),
    sa.Column('bank_swift', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('currency_display', sa.String(length=10), nullable=False),
    sa.Column('date_format', sa.String(length=30), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('invoice_prefix', sa.String(length=20), nullable=False),
    sa.Column('next_invoice_no', sa.Integer(), nullable=False),
    sa.Column('quotation_prefix', sa.String(length=20), nullable=False),
    sa.Column('next_quotation_no', sa.Integer(), nullable=False),
    sa.Column('show_govt_fee_on_invoice', sa.Boolean(), nullable=False),
    sa.Column('default_vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('default_invoice_notes_cash', sa.String(length=2000), nullable=True),
    sa.Column('default_invoice_terms_cash', sa.String(length=2000), nullable=True),
    sa.Column('default_invoice_notes_credit', sa.String(length=2000), nullable=True),
    sa.Column('default_invoice_terms_credit', sa.String(length=2000), nullable=True),
    sa.Column('default_quotation_validity_days', sa.Integer(), nullable=False),
    sa.Column('default_quotation_notes', sa.String(length=2000), nullable=True),
    sa.Column('default_quotation_terms', sa.String(length=2000), nullable=True),
    sa.Column('template_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)
    op.create_table('users',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'employee', name='userrole'), nullable=False),
    sa.Column('avatar_color', sa.String(length=20), nullable=True),
    sa.Column('phone_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_table('businesses')
    # ### end Alembic commands ###
