"""add auto_lock_minutes to users

Revision ID: fec7d19708ea
Revises: c1efc82196c2
Create Date: 2026-08-29 01:04:46.427609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec7d19708ea'
down_revision: Union[str, None] = 'c1efc82196c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('auto_lock_minutes', sa.Integer(), nullable=False, server_default='15'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auto_lock_minutes')
    # ### end Alembic commands ###
